"""
gan_runner.py
-------------
GAN pipeline runner — completely separate from the CV pipeline.

Reads CV outputs (segmentation result) and produces a new .gltf in
gan_output/<stem>/ that contains:
  - The original CV 3D building (walls, doors, windows)
  - A new interior 3D mesh generated by GAN + MiDaS depth

Usage
-----
    python -m gan_part.gan_runner                    # all samples
    python -m gan_part.gan_runner samples/floorplan1.png

Swap backend to your trained GAN:
    Set GAN_CHECKPOINT = "gan_part/checkpoints/final.pt"
    Set BACKEND = "gan"
"""

from __future__ import annotations

import json
import base64
import struct
import sys
import os
from pathlib import Path
from typing import Optional

import cv2
import numpy as np
from PIL import Image

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

# ── Config — swap these when your GAN is ready ────────────────────────────────
BACKEND        = "controlnet"          # "controlnet" | "gan"
GAN_CHECKPOINT = None                  # "gan_part/checkpoints/final.pt"
DEVICE         = "cpu"
GAN_OUTPUT_DIR = PROJECT_ROOT / "gan_output"

# ── Imports ───────────────────────────────────────────────────────────────────
from src.segmentation.predictor import FloorPlanPredictor
from src.geometry.pipeline import GeometryPipeline
from src.reconstruction.pipeline import ReconstructionPipeline
from src.reconstruction.extruder import Extruder

from gan_part.data.preprocessor import build_seg_map_from_elements
from gan_part.inference.room_renderer import RoomRenderer
from gan_part.inference.depth_pipeline import DepthEstimator
from gan_part.inference.interior_mesh import depth_to_interior_mesh

MODEL_PATH = PROJECT_ROOT / "models" / "best.pt"

# ── Lazy-loaded singletons ────────────────────────────────────────────────────
_renderer      = None
_depth_estimator = None


def get_renderer() -> RoomRenderer:
    global _renderer
    if _renderer is None:
        print(f"  Loading {'ControlNet' if BACKEND == 'controlnet' else 'GAN'} renderer...")
        _renderer = RoomRenderer(
            backend=BACKEND,
            gan_checkpoint=GAN_CHECKPOINT,
            device=DEVICE,
        )
    return _renderer


def get_depth_estimator() -> DepthEstimator:
    global _depth_estimator
    if _depth_estimator is None:
        _depth_estimator = DepthEstimator(device=DEVICE)
    return _depth_estimator


# ── Core pipeline ─────────────────────────────────────────────────────────────

def process_floorplan(image_path: Path) -> Optional[Path]:
    """
    Full GAN pipeline for one floorplan image.
    Returns path to the output .gltf or None on failure.
    """
    stem    = image_path.stem
    out_dir = GAN_OUTPUT_DIR / stem
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n{'='*60}")
    print(f"GAN Pipeline: {image_path.name}")
    print(f"Output → gan_output/{stem}/")
    print(f"{'='*60}")

    # ── Step 1: CV — detection + geometry + 3D building ──────────────
    print("\n[1/4] CV: Detection + Geometry + 3D building...")

    best_result = None
    for conf in [0.35, 0.25, 0.15, 0.10, 0.05]:
        predictor  = FloorPlanPredictor(str(MODEL_PATH), confidence=conf, device="cpu")
        seg_result = predictor.predict(str(image_path))
        if seg_result.summary["total_elements"] > 0 and best_result is None:
            best_result = seg_result
            print(f"  Detections: {seg_result.summary['by_class']}")

    if best_result is None:
        print("  ⚠ No detections — skipping.")
        return None

    img = cv2.imread(str(image_path))
    geo_result, _, _ = GeometryPipeline().run_and_visualize(
        best_result, img,
        image_path=str(image_path),
        output_dir=str(PROJECT_ROOT / "outputs" / "geometry"),
    )
    print(f"  Scale: {geo_result.scale.pixels_per_metre:.1f} px/m")

    # Get building footprint extents (in metres) for mesh placement
    extruder = Extruder(
        wall_height=2.8,
        pixels_per_metre=geo_result.scale.pixels_per_metre,
    )
    all_pts = []
    for poly in geo_result.vectorization.all_polygons:
        if poly.points:
            all_pts.extend(poly.points)
    for elem in best_result.elements:
        x1, y1, x2, y2 = elem.bbox
        all_pts.extend([(x1, y1), (x2, y2)])

    if all_pts:
        origin = np.array(all_pts, dtype=np.float32).mean(axis=0)
        extruder.set_global_origin(origin)

    # Build CV 3D model (walls/doors/windows) — no render texture
    cv_model = ReconstructionPipeline().reconstruct(
        geo_result,
        output_dir=str(out_dir),
        stem=stem,
        floorplan_image_path=str(image_path),
        render_image_path=None,
    )
    print(f"  CV model: {cv_model.building.vertex_count} vertices")

    # Get building footprint in metres from the CV model
    verts = cv_model.building.merged_vertices
    bx_min, bx_max = float(verts[:, 0].min()), float(verts[:, 0].max())
    by_min, by_max = float(verts[:, 1].min()), float(verts[:, 1].max())

    # ── Step 2: GAN — generate interior render ────────────────────────
    print(f"\n[2/4] GAN: Generating interior render ({BACKEND})...")
    seg_map = build_seg_map_from_elements(
        best_result.elements,
        best_result.image_shape,
    )
    room_counts = {}
    for e in best_result.elements:
        room_counts[e.class_name] = room_counts.get(e.class_name, 0) + 1
    room_label = max(room_counts, key=room_counts.get) if room_counts else "default"

    render_img = get_renderer().render(seg_map, room_label=room_label)
    render_path = out_dir / f"{stem}_render.png"
    render_img.save(str(render_path))
    print(f"  ✓ Render saved → {render_path.name}")

    # ── Step 3: MiDaS — depth estimation ─────────────────────────────
    print("\n[3/4] MiDaS: Depth estimation...")
    depth_map = get_depth_estimator().estimate(render_img)
    depth_img = Image.fromarray((depth_map * 255).astype(np.uint8))
    depth_path = out_dir / f"{stem}_depth.png"
    depth_img.save(str(depth_path))
    print(f"  ✓ Depth map saved → {depth_path.name}")

    # ── Step 4: Build interior mesh + combine with CV model ───────────
    print("\n[4/4] Building interior 3D mesh + combining with CV model...")
    vertices, faces, colours = depth_to_interior_mesh(
        render_img,
        depth_map,
        building_x_min=bx_min,
        building_x_max=bx_max,
        building_y_min=by_min,
        building_y_max=by_max,
        floor_z=0.02,
        depth_scale=1.2,
        grid_size=128,
    )
    print(f"  Interior mesh: {len(vertices)} vertices, {len(faces)} faces")

    # Write combined .gltf
    gltf_path = _write_combined_gltf(
        cv_model=cv_model,
        interior_vertices=vertices,
        interior_faces=faces,
        interior_colours=colours,
        render_image=render_img,
        out_dir=out_dir,
        stem=stem,
        floorplan_image_path=str(image_path),
    )
    print(f"\n  ✓ Combined .gltf → {gltf_path.name}")
    print(f"  Open at: https://gltf-viewer.donmccurdy.com")
    return gltf_path


# ── glTF writer ───────────────────────────────────────────────────────────────

def _write_combined_gltf(
    cv_model,
    interior_vertices: np.ndarray,
    interior_faces: np.ndarray,
    interior_colours: np.ndarray,
    render_image: Image.Image,
    out_dir: Path,
    stem: str,
    floorplan_image_path: str,
) -> Path:
    """
    Write a .gltf that contains:
      1. CV building mesh (walls, doors, windows) — vertex colours
      2. Interior 3D mesh — textured with the GAN render
      3. Ground plane — floorplan image texture
    """
    gltf_path = out_dir / f"{stem}_interior.gltf"

    def pad4(b: bytes) -> bytes:
        r = len(b) % 4
        return b + b"\x00" * (4 - r) if r else b

    buffers_data = b""
    buffer_views = []
    accessors    = []
    meshes       = []
    nodes        = []
    materials    = []
    textures     = []
    images_list  = []

    def add_buffer(data: bytes, target: Optional[int] = None) -> int:
        nonlocal buffers_data
        padded = pad4(data)
        bv = {"buffer": 0, "byteOffset": len(buffers_data), "byteLength": len(padded)}
        if target:
            bv["target"] = target
        buffer_views.append(bv)
        buffers_data += padded
        return len(buffer_views) - 1

    def add_accessor(bv_idx, comp_type, count, acc_type,
                     min_v=None, max_v=None) -> int:
        acc = {"bufferView": bv_idx, "componentType": comp_type,
               "count": count, "type": acc_type}
        if min_v is not None: acc["min"] = min_v
        if max_v is not None: acc["max"] = max_v
        accessors.append(acc)
        return len(accessors) - 1

    def load_img_b64(path_or_pil) -> Optional[str]:
        try:
            if isinstance(path_or_pil, (str, Path)):
                img = cv2.imread(str(path_or_pil))
                if img is None: return None
                img = cv2.flip(img, 0)
                ok, buf = cv2.imencode(".png", img)
                if not ok: return None
                return base64.b64encode(buf.tobytes()).decode("ascii")
            else:
                import io
                buf = io.BytesIO()
                path_or_pil.save(buf, format="PNG")
                return base64.b64encode(buf.getvalue()).decode("ascii")
        except Exception:
            return None

    def triangulate(faces_list):
        tris = []
        for f in faces_list:
            if len(f) < 3: continue
            if len(f) == 3:
                tris.append(f)
            else:
                for i in range(1, len(f) - 1):
                    tris.append([f[0], f[i], f[i+1]])
        return tris

    # ── 1. CV building mesh (walls/doors/windows) ─────────────────────
    cv_verts  = cv_model.building.merged_vertices.astype(np.float32)
    cv_colors = cv_model.building.merged_colors.astype(np.float32)
    cv_tris   = np.array(
        triangulate(cv_model.building.merged_faces), dtype=np.uint32
    ).flatten()

    if len(cv_tris) > 0:
        bv_v = add_buffer(cv_verts.tobytes(), 34962)
        bv_c = add_buffer(cv_colors.tobytes(), 34962)
        bv_i = add_buffer(cv_tris.tobytes(), 34963)

        acc_v = add_accessor(bv_v, 5126, len(cv_verts), "VEC3",
                             cv_verts.min(0).tolist(), cv_verts.max(0).tolist())
        acc_c = add_accessor(bv_c, 5126, len(cv_verts), "VEC3")
        acc_i = add_accessor(bv_i, 5125, len(cv_tris), "SCALAR")

        materials.append({
            "name": "Building",
            "pbrMetallicRoughness": {
                "metallicFactor": 0.0,
                "roughnessFactor": 0.9,
            },
        })
        meshes.append({
            "name": "CVBuilding",
            "primitives": [{
                "attributes": {"POSITION": acc_v, "COLOR_0": acc_c},
                "indices": acc_i,
                "mode": 4,
                "material": len(materials) - 1,
            }]
        })
        nodes.append({"mesh": len(meshes) - 1, "name": "CVBuilding"})

    # ── 2. Interior mesh (GAN + MiDaS) ───────────────────────────────
    int_verts   = interior_vertices.astype(np.float32)
    int_colours = interior_colours.astype(np.float32)
    int_tris    = interior_faces.astype(np.uint32).flatten()

    # Build UV coords — map each vertex back to render image UV
    # Vertices are laid out in a grid, so UV = normalised grid position
    G = int(np.sqrt(len(int_verts)))
    u = np.tile(np.linspace(0, 1, G), G).astype(np.float32)
    v = np.repeat(np.linspace(0, 1, G), G).astype(np.float32)
    int_uvs = np.stack([u, v], axis=1).astype(np.float32)

    # Embed render image as texture
    render_b64 = load_img_b64(render_image)
    render_mat_idx = None
    if render_b64:
        images_list.append({"uri": f"data:image/png;base64,{render_b64}"})
        tex_idx = len(textures)
        textures.append({"source": len(images_list) - 1})
        render_mat_idx = len(materials)
        materials.append({
            "name": "InteriorRender",
            "pbrMetallicRoughness": {
                "baseColorTexture": {"index": tex_idx},
                "metallicFactor": 0.0,
                "roughnessFactor": 0.8,
            },
            "doubleSided": True,
        })

    bv_iv  = add_buffer(int_verts.tobytes(), 34962)
    bv_iuv = add_buffer(int_uvs.tobytes(), 34962)
    bv_ii  = add_buffer(int_tris.tobytes(), 34963)

    acc_iv  = add_accessor(bv_iv,  5126, len(int_verts), "VEC3",
                           int_verts.min(0).tolist(), int_verts.max(0).tolist())
    acc_iuv = add_accessor(bv_iuv, 5126, len(int_verts), "VEC2")
    acc_ii  = add_accessor(bv_ii,  5125, len(int_tris),  "SCALAR")

    int_prim = {
        "attributes": {"POSITION": acc_iv, "TEXCOORD_0": acc_iuv},
        "indices": acc_ii,
        "mode": 4,
    }
    if render_mat_idx is not None:
        int_prim["material"] = render_mat_idx

    meshes.append({"name": "InteriorMesh", "primitives": [int_prim]})
    nodes.append({"mesh": len(meshes) - 1, "name": "InteriorMesh"})

    # ── 3. Ground plane — floorplan texture ──────────────────────────
    fp_b64 = load_img_b64(floorplan_image_path)
    if fp_b64:
        images_list.append({"uri": f"data:image/png;base64,{fp_b64}"})
        fp_tex_idx = len(textures)
        textures.append({"source": len(images_list) - 1})
        fp_mat_idx = len(materials)
        materials.append({
            "name": "FloorPlan",
            "pbrMetallicRoughness": {
                "baseColorTexture": {"index": fp_tex_idx},
                "metallicFactor": 0.0,
                "roughnessFactor": 1.0,
            },
            "doubleSided": True,
        })

        verts_all = cv_model.building.merged_vertices
        xmn, xmx = float(verts_all[:,0].min()), float(verts_all[:,0].max())
        ymn, ymx = float(verts_all[:,1].min()), float(verts_all[:,1].max())
        z = -0.001
        gp_v = np.array([
            [xmn, ymn, z], [xmx, ymn, z],
            [xmx, ymx, z], [xmn, ymx, z],
        ], dtype=np.float32)
        gp_uv  = np.array([[0,0],[1,0],[1,1],[0,1]], dtype=np.float32)
        gp_idx = np.array([0,1,2, 0,2,3], dtype=np.uint32)

        bv_gv  = add_buffer(gp_v.tobytes(), 34962)
        bv_guv = add_buffer(gp_uv.tobytes(), 34962)
        bv_gi  = add_buffer(gp_idx.tobytes(), 34963)

        acc_gv  = add_accessor(bv_gv,  5126, 4, "VEC3",
                               gp_v.min(0).tolist(), gp_v.max(0).tolist())
        acc_guv = add_accessor(bv_guv, 5126, 4, "VEC2")
        acc_gi  = add_accessor(bv_gi,  5125, 6, "SCALAR")

        meshes.append({"name": "FloorPlan", "primitives": [{
            "attributes": {"POSITION": acc_gv, "TEXCOORD_0": acc_guv},
            "indices": acc_gi,
            "mode": 4,
            "material": fp_mat_idx,
        }]})
        nodes.append({"mesh": len(meshes) - 1, "name": "FloorPlan"})

    # ── Assemble glTF ─────────────────────────────────────────────────
    gltf = {
        "asset": {"version": "2.0", "generator": "Floor2Model-GAN"},
        "scene": 0,
        "scenes": [{"nodes": list(range(len(nodes)))}],
        "nodes": nodes,
        "meshes": meshes,
        "accessors": accessors,
        "bufferViews": buffer_views,
        "buffers": [{
            "byteLength": len(buffers_data),
            "uri": "data:application/octet-stream;base64,"
                   + base64.b64encode(buffers_data).decode("ascii"),
        }],
    }
    if materials:    gltf["materials"]  = materials
    if textures:     gltf["textures"]   = textures
    if images_list:  gltf["images"]     = images_list

    with open(gltf_path, "w") as f:
        json.dump(gltf, f, indent=2)

    return gltf_path


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) > 1:
        # Single image passed as argument
        images = [Path(a) for a in sys.argv[1:] if Path(a).exists()]
    else:
        # All samples
        exts = ("*.png", "*.jpg", "*.jpeg", "*.bmp", "*.tiff", "*.tif")
        images = sorted(
            p for ext in exts
            for p in (PROJECT_ROOT / "samples").glob(ext)
        )

    if not images:
        print("❌ No images found. Pass image paths or put images in samples/")
        sys.exit(1)

    print(f"Found {len(images)} image(s)")
    print(f"Backend: {BACKEND}")
    print(f"Output:  gan_output/\n")

    for img_path in images:
        try:
            result = process_floorplan(img_path)
            if result:
                print(f"✓ {img_path.name} → {result}")
        except Exception as e:
            print(f"✗ {img_path.name} failed: {e}")
            import traceback
            traceback.print_exc()

    print(f"\n{'='*60}")
    print(f"✓ Done → gan_output/")
    print(f"{'='*60}")
